name: C++ Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-18.04
    container: axsauze/kompute-builder:0.1

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      run: |
        cmake -Bbuild/ \
                  -DKOMPUTE_OPT_INSTALL=0                    \
                  -DKOMPUTE_OPT_REPO_SUBMODULE_BUILD=1       \
                  -DKOMPUTE_OPT_BUILD_TESTS=1                \
                  -DKOMPUTE_OPT_ENABLE_SPDLOG=1              \
                  -DSPDLOG_INSTALL=1
    - name: build
      run: |
        make mk_build_tests
    - name: test
      run: |
        export VK_ICD_FILENAMES=/swiftshader/vk_swiftshader_icd.json
        make mk_run_tests_cpu_only

